# Generated by Django 3.2.23 on 2024-02-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieRecommender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.CharField(default='wwwwwwww', max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.CharField(default='wsdfe', max_length=70),
            preserve_default=False,
        ),
    ]
